name: her_driver_app
description: A ride sharing Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.7
  http: ^1.4.0
  connectivity_plus: ^6.1.4
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  country_code_picker: ^3.3.0
  dotted_border: ^3.1.0
  flutter_svg: ^2.2.0
  flutter_switch: ^0.3.2
  percent_indicator: ^4.2.5
  syncfusion_flutter_datepicker: ^30.1.40
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_animarker: ^3.2.0
  file_picker: ^10.1.8
  readmore: ^3.0.0
  url_launcher: ^6.3.2
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: ^0.17.0
  flutter_rating_bar: ^4.0.1
  vibration: ^3.1.3
  shimmer: ^3.0.0
  expandable: ^5.0.1
  appinio_swiper: ^2.1.1
  pin_code_fields: ^8.0.1
  fl_chart: ^0.69.2
  custom_map_markers: ^0.0.2+1
  flutter_polyline_points: ^2.1.0
  path: ^1.9.1
  flutter_spinkit: ^5.2.1
  device_info_plus: ^9.0.0
  location: 8.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_typeahead: ^5.2.0
  permission_handler: ^12.0.1
  flutter_inappwebview: ^6.1.5
  fluttertoast: ^8.2.12
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable.git
      ref: master
  sliding_up_panel: ^2.0.0+1
  flutter_animated_button: ^2.0.4
  audioplayers: ^6.5.0
  card_swiper: ^3.0.1
  lottie: ^3.3.1
  app_settings: ^6.1.1
  showcaseview: ^4.0.1
  dart_pusher_channels: ^1.2.3
  just_the_tooltip: ^0.0.12
  firebase_crashlytics: ^4.3.9
  share_plus: ^11.0.0
  flutter_keyboard_visibility: ^6.0.0
  cloud_firestore: ^5.6.11
  agora_rtc_engine: ^6.2.3
  firebase_storage: ^12.3.0
  video_thumbnail: ^0.5.6
  video_player: ^2.10.0
  chewie: ^1.12.1
  firebase_auth: ^5.6.2
  phone_numbers_parser: ^9.0.3
  flutter_downloader: ^1.12.0
  square_progress_indicator: ^0.0.8

dependency_overrides:
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/
    - assets/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
